import type { Config } from "tailwindcss";

export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-base": "#0B0F19",
        surface: "#051424",
        "surface-dim": "#051424",
        "surface-bright": "#2c3a4c",
        "surface-container-lowest": "#010f1f",
        "surface-container-low": "#0d1c2d",
        "surface-container": "#122131",
        "surface-container-high": "#1c2b3c",
        "surface-container-highest": "#273647",
        "on-surface": "#d4e4fa",
        "on-surface-variant": "#c7c4d7",
        primary: "#c0c1ff",
        "on-primary": "#1000a9",
        "primary-container": "#8083ff",
        "on-primary-container": "#0d0096",
        "primary-fixed": "#e1e0ff",
        "primary-fixed-dim": "#c0c1ff",
        "inverse-primary": "#494bd6",
        secondary: "#4edea3",
        "on-secondary": "#003824",
        "secondary-container": "#00a572",
        "secondary-fixed": "#6ffbbe",
        "secondary-fixed-dim": "#4edea3",
        tertiary: "#ffb95f",
        "on-tertiary": "#472a00",
        "tertiary-container": "#ca8100",
        "tertiary-fixed": "#ffddb8",
        "tertiary-fixed-dim": "#ffb95f",
        error: "#ffb4ab",
        "on-error": "#690005",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",
        outline: "#908fa0",
        "outline-variant": "#464554",
        background: "#051424",
        "on-background": "#d4e4fa",
        "surface-tint": "#c0c1ff",
        "surface-variant": "#273647",
        "inverse-surface": "#d4e4fa",
        "inverse-on-surface": "#233143",
        // Light mode tokens
        "light-surface": "#f8f9ff",
        "light-surface-dim": "#ccdbf3",
        "light-surface-bright": "#f8f9ff",
        "light-surface-container": "#e6eeff",
        "light-surface-container-high": "#dce9ff",
        "light-surface-container-highest": "#d5e3fc",
        "light-on-surface": "#0d1c2e",
        "light-on-surface-variant": "#464554",
        "light-primary": "#4648d4",
        "light-on-primary": "#ffffff",
        "light-primary-container": "#6063ee",
        "light-on-primary-container": "#fffbff",
        "light-secondary": "#565e74",
        "light-on-secondary": "#ffffff",
        "light-secondary-container": "#dae2fd",
        "light-background": "#f8f9ff",
        "light-on-background": "#0d1c2e",
        "light-outline": "#767586",
        "light-outline-variant": "#c7c4d7",
        "light-error": "#ba1a1a",
        "light-on-error": "#ffffff",
        "light-error-container": "#ffdad6",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        "2xl": "0.75rem",
      },
      fontFamily: {
        sans: ["Inter", "system-ui", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
        label: ["Geist", "sans-serif"],
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "1.1", letterSpacing: "-0.04em", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "1.2", letterSpacing: "-0.03em", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "1.3", letterSpacing: "-0.02em", fontWeight: "500" }],
        "body-lg": ["16px", { lineHeight: "1.6", letterSpacing: "-0.01em", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "1.5", letterSpacing: "0em", fontWeight: "400" }],
        "label-md": ["12px", { lineHeight: "1", letterSpacing: "0.02em", fontWeight: "500" }],
        "mono-sm": ["12px", { lineHeight: "1.4", fontWeight: "400" }],
      },
      spacing: {
        xs: "0.25rem",
        sm: "0.5rem",
        md: "1rem",
        lg: "1.5rem",
        xl: "2rem",
        "2xl": "4rem",
        gutter: "1.5rem",
      },
    },
  },
  plugins: [],
} satisfies Config;
